---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "toolbox"
subtitle: "fluig"
logo: "assets/fluig.png"
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>'  # set false if you want to hide it.

services:
  - name: "No-Code Prod"
    icon: "fas fa-tools"
    items:
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Metric analytics & dashboards"
        url: "https://grafana.fluig.app/"
        target: '_blank'
      - name: "Prometheus"
        logo: "assets/tools/prometheus.webp"
        subtitle: "Monitoring and metrics"
        url: "https://prometheus.fluig.app/"
        target: '_blank'
      - name: "AlertManager"
        logo: "assets/tools/prometheus.webp"
        url: "https://alertmanager.fluig.app/"
        target: '_blank'
      - name: "Kibana"
        logo: "assets/tools/kibana.png"
        url: "https://kibana.fluig.app/"
        target: '_blank'
      - name: "RabbitMQ"
        logo: "assets/tools/rabbitmq.png"
        url: "https://rabbitmq-cluster.fluig.app/"
        target: '_blank'
      - name: "RabbitMQ Connector"
        logo: "assets/tools/rabbitmq.png"
        url: "https://rabbitmq-connector.fluig.app/"
        target: '_blank'
      - name: "Logs and Database access"
        logo: "assets/tools/logs.png"
        url: "https://tdn.totvs.com/pages/viewpage.action?pageId=465390867"
        target: '_blank'
  - name: "No-Code Dev (Homolog/QA)"
    icon: "fas fa-tools"
    items:
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Metric analytics & dashboards"
        url: "https://grafana.fluig.io/"
        target: '_blank'
      - name: "Prometheus"
        logo: "assets/tools/prometheus.webp"
        subtitle: "Monitoring and metrics"
        url: "https://prometheus.fluig.io/"
        target: '_blank'
      - name: "AlertManager"
        logo: "assets/tools/prometheus.webp"
        url: "https://alertmanager.fluig.io/"
        target: '_blank'
      - name: "Kibana"
        logo: "assets/tools/kibana.png"
        url: "https://kibana.fluig.io/"
        target: '_blank'
      - name: "RabbitMQ"
        logo: "assets/tools/rabbitmq.png"
        url: "https://rabbitmq.fluig.io/"
        target: '_blank'
      - name: "RabbitMQ Connector Homolog"
        logo: "assets/tools/rabbitmq.png"
        url: "http://rabbitmq-connector-homolog.fluig.io/"
        target: '_blank'
      - name: "RabbitMQ Connector QA"
        logo: "assets/tools/rabbitmq.png"
        url: "http://rabbitmq-connector.qa.fluig.io/"
        target: '_blank'
      - name: "Logs and Database access"
        logo: "assets/tools/logs.png"
        url: "https://tdn.totvs.com/pages/viewpage.action?pageId=465390867"
        target: '_blank'
  - name: "Identity Prod"
    icon: "fas fa-tools"
    items:
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Metric analytics & dashboards"
        url: "https://grafana.fluigidentity.com/"
        target: '_blank'
      - name: "Prometheus"
        logo: "assets/tools/prometheus.webp"
        subtitle: "Monitoring and metrics"
        url: "https://prometheus.cluster.k8s-idm3-prod-sa-east-1.fluig.io/"
        target: '_blank'
      - name: "AlertManager"
        logo: "assets/tools/prometheus.webp"
        url: "http://alertmanager.cluster.k8s-idm3-prod-sa-east-1.fluig.io/"
        target: '_blank'
      - name: "Kibana"
        logo: "assets/tools/kibana.png"
        subtitle: 'Kibana events'
        url: "http://kibana.cluster.k8s-idm3-prod-sa-east-1.fluig.io/"
        target: '_blank'
      - name: "RabbitMQ"
        logo: "assets/tools/rabbitmq.png"
        url: "https://rabbitmq.fluigidentity.com/"
        target: '_blank'
  - name: "Identity Homolog"
    icon: "fas fa-tools"
    items:
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Metric analytics & dashboards"
        url: "https://grafana.customerfi.com/"
        target: '_blank'
      - name: "Prometheus"
        logo: "assets/tools/prometheus.webp"
        subtitle: "Monitoring and metrics"
        url: "https://prometheus.cluster.k8s-idm1-dev-us-east-1.fluig.io/"
        target: '_blank'
      - name: "AlertManager"
        logo: "assets/tools/prometheus.webp"
        url: "http://alertmanager.cluster.k8s-idm1-dev-us-east-1.fluig.io/"
        target: '_blank'
      - name: "Kibana"
        logo: "assets/tools/kibana.png"
        subtitle: 'Kibana events'
        url: "http://kibana.cluster.k8s-idm1-dev-us-east-1.fluig.io/"
        target: '_blank'
      - name: "RabbitMQ"
        logo: "assets/tools/rabbitmq.png"
        url: "https://rabbitmq.customerfi.com/"
        target: '_blank'
  - name: "Identity QA"
    icon: "fas fa-tools"
    items:
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Metric analytics & dashboards"
        url: "https://grafana.fluigidentity.net/"
        target: '_blank'
      - name: "Prometheus"
        logo: "assets/tools/prometheus.webp"
        subtitle: "Monitoring and metrics"
        url: "https://prometheus.cluster.k8s-idm4-dev-us-east-1.fluig.io/"
        target: '_blank'
      - name: "AlertManager"
        logo: "assets/tools/prometheus.webp"
        url: "http://alertmanager.cluster.k8s-idm4-dev-us-east-1.fluig.io/"
        target: '_blank'
      - name: "Kibana"
        logo: "assets/tools/kibana.png"
        subtitle: 'Kibana events'
        url: "http://kibana.cluster.k8s-idm4-dev-us-east-1.fluig.io/"
        target: '_blank'
      - name: "RabbitMQ"
        logo: "assets/tools/rabbitmq.png"
        url: "https://rabbitmq.fluigidentity.net/"
        target: '_blank'
  - name: "Status"
    icon: "fas fa-heartbeat"
    items:
      - name: "Status fluig"
        logo: "assets/fluig.png"
        subtitle: "Public status page"
        url: "https://status.fluig.com/"
        target: '_blank'
      - name: "Status Identity"
        logo: "assets/fluig.png"
        subtitle: "Public status page"
        url: "http://status.fluigidentity.com/"
        target: '_blank'